In [1]:
print('Hello World') #first

Hello World


In [2]:
a=int(input('Enter first number'))
b=int(input('Enter second number'))
c=a+b
print(c) #second

Enter first number4
Enter second number3
7


In [3]:
import math
a=int(input('Enter any number'))
b=math.sqrt(a)
print(b) #third

Enter any number43
6.557438524302


In [4]:
a=float(input('Enter first side'))
b=float(input('Enter second side'))
c=float(input('Enter third side'))
s=(a+b+c)/2
area=(s*(s-a)*(s-b)*(s-c))**0.5
print(area) #fourth

Enter first side43
Enter second side43
Enter third side43
800.6404857987135


In [5]:
import cmath
a=int(input('Enter value of a'))
b=int(input('Enter value of b'))
c=int(input('Enter value of c'))
d=(b**2)-(4*a*c)
r1=(-b+cmath.sqrt(d))/(2*a)
r2=(-b-cmath.sqrt(d))/(2*a)
print(r1)
print(r2) #fifth

Enter value of a3
Enter value of b4
Enter value of c2
(-0.6666666666666666+0.47140452079103173j)
(-0.6666666666666666-0.47140452079103173j)


In [6]:
a=int(input('Enter value of a'))
b=int(input('Enter value of b'))
c=a
a=b
b=c
print(a)
print(b) #sixth

Enter value of a4
Enter value of b3
3
4


In [7]:
import random
print(random.randint(20,50)) #seventh

35


In [8]:
a=float(input('Enter value in km'))
miles=a*0.621371
print(miles)#eighth

Enter value in km333
206.916543


In [9]:
a=float(input('Enter value in Celsius'))
f=((9/5)*a)+32
print(f)

Enter value in Celsius43
109.4


In [10]:
a=int(input('Enter any number'))
if a>0:
    print('Positive')
elif a<0:
    print('Negative')
else:
    print('Zero')


Enter any number4
Positive


In [11]:
a=int(input('Enter any number'))
if a%2==0:
    print('Even')
else:
    print('Odd')

Enter any number3
Odd


In [12]:
a=int(input('Enter any year'))
if a%4==0:
    print('Leap year')
elif a<0:
    print('Not a leap year')

Enter any year4
Leap year


In [13]:
a=int(input('Enter any number'))
b=int(input('Enter any number'))
c=int(input('Enter any number'))
if a>b and a>c:
    print('A is largest')
elif b>a and b>c:
    print('B is largest')
else:
    print('C is largest')

Enter any number5
Enter any number3
Enter any number5
C is largest


In [14]:
a=int(input('Enter any number'))
if a>1:
    for i in range(2,int(a/2)+1):
        if a%i==0:
            print('Not a prime number')
            break
    else:
            print('Prime number')
else:
    print('Not prime')

Enter any number23
Prime number


In [15]:

for a in range(1,100):
    if a>1:
        for i in range(2,a):
            if a%i==0:
                break
        else:
            print(a)


2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [16]:
a=int(input('Enter any number'))
fact=1
if a==0:
    print('Factorial is 1')
elif a<0:
    print('Please enter a positive number')
else:
    for i in range(1,a+1):
        fact=fact*i
    print(fact)


Enter any number23
25852016738884976640000


In [17]:
a=int(input('Enter any number'))
op=1
for i in range(1,11):
    print(a*i)

Enter any number2
2
4
6
8
10
12
14
16
18
20


In [18]:
a=int(input('Enter any number'))
x1=0
x2=1
c=0
if a==1:
    print(x1)
elif a<1:
    print('Enter a positive number')
else:
    while c<a:
        print(x1)
        x=x1+x2
        x1=x2
        x2=x
        c+=1 #fib

Enter any number32
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269


In [19]:
a=int(input('Enter any number'))
sum=0
c=a
while c>0:
    x=c%10
    sum+=x**3
    c=c//10
if a==sum:
    print('Armstrong')
else:
    print('Not Armstrong')
    

Enter any number434
Not Armstrong


In [23]:



for i in range(100,1000):
    order=len(str(i))
    sum=0
    c=i
    while c>0:
        x=c%10
        sum+=x**3
        c=c//10
    if i==sum:
        print(i)
    #arm series
    

153
370
371
407


In [24]:
a=int(input('Enter any number'))
if a<0:
    print('Enter a positive num')
else:
    sum=0
    while(a>0):
        sum+=a
        a-=1
    print(sum)

Enter any number5
15


In [26]:
n=10
final_list= list(map(lambda x: 2**x,range(n)))
for i in range(n):
    print('2 raised to the power',i,'is',final_list[i])

2 raised to the power 0 is 1
2 raised to the power 1 is 2
2 raised to the power 2 is 4
2 raised to the power 3 is 8
2 raised to the power 4 is 16
2 raised to the power 5 is 32
2 raised to the power 6 is 64
2 raised to the power 7 is 128
2 raised to the power 8 is 256
2 raised to the power 9 is 512


In [6]:
l=[10,32,232,32,21,4,53]
op=list(filter(lambda x:(x%5==0),l))
print(op)

[10]


In [7]:
a=int(input('Enter any number'))
b=bin(a)
o=oct(a)
h=hex(a)
print('Binary',b,'Octal',o,'Hexadecimal',h)

Enter any number4
Binary 0b100 Octal 0o4 Hexadecimal 0x4


In [8]:
a=input('Enter letter')
b=ord(a)
print(b)


Enter letterA
65


In [9]:
def gcd(a, b):
    if(b == 0):
        return a
    else:
        return gcd(b, a % b)
  
a = 50
b = 20
print("The gcd of 50 and 20 is : ", end="")
print(gcd(50, 20))

The gcd of 50 and 20 is : 10


In [10]:
def lcm(a,b):
    if a>b:
        greater=a
    else:
        greater=b
    while(True):
        if((greater%a==0) and (greater%b==0)):
            lcm=greater
            break
        greater=greater+1
    return lcm
x=int(input('Enter any number'))
y=int(input('Enter any number'))
lcm(x,y)

Enter any number6
Enter any number5


30

In [14]:
def factors(n):
    i=1
    while i<=n:
        if(n%i==0):
            print(i)
        i=i+1
a=30
factors(a)

1
2
3
5
6
10
15
30


In [2]:
def add(x,y):
    a= x+y
    print(a)
def sub(x,y):
    a= x-y
    print(a)
def mul(x,y):
    a= x*y
    print(a)
def div(x,y):
    a= x/y
    print(a)
add(10,5)
sub(10,5)
mul(10,5)
div(10,5)

15
5
50
2.0


In [3]:
import itertools
import random
card_list= list(itertools.product(range(1,14),['Hearts','Diamonds','Spades','Club']))
random.shuffle(card_list)
for i in range(5):
    print(card_list[i][0],card_list[i][1])

10 Diamonds
4 Hearts
4 Club
11 Spades
11 Hearts


In [1]:
import calendar
yy = int(input("Enter year: "))
mm = int(input("Enter month: "))
print(calendar.month(yy, mm))

Enter year: 2021
Enter month: 9
   September 2021
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30



In [3]:
def fib(n):
   if n <= 1:
       return n
   else:
       return(fib(n-1) + fib(n-2))
nterms = 10
if nterms <= 0:
   print("Plese enter a positive integer")
else:
   for i in range(nterms):
       print(fib(i))

0
1
1
2
3
5
8
13
21
34


In [4]:
def sum(n):
   if n <= 1:
       return n
   else:
       return n + sum(n-1)
num = 27
if num < 0:
   print("Enter a positive number")
else:
   print(sum(num))

378


In [6]:
def fact(n):
   if n == 1:
       return n
   else:
       return n*fact(n-1)
num = 5
if num < 0:
   print("Enter a positive number")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   print(fact(num))


120


In [7]:
def bin(n):
   if n > 1:
       bin(n//2)
   print(n % 2,end = '')
n = 22
bin(n)
print()

10110


In [9]:
A = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

B = [[10,11,12],
    [13,14,15],
    [16,17,18]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
for i in range(len(A)):
   for j in range(len(A[0])):
       result[i][j] = A[i][j] + B[i][j]
for r in result:
   print(r)

[11, 13, 15]
[17, 19, 21]
[23, 25, 27]


In [11]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, end ='\n\n') 
#after
print(arr.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
A = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

B = [[10,11,12],
    [13,14,15],
    [16,17,18]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
for i in range(len(A)):
   for j in range(len(A[0])):
       result[i][j] = A[i][j] * B[i][j]
for r in result:
   print(r)

[10, 22, 36]
[52, 70, 90]
[112, 136, 162]


In [14]:
def isPalindrome(s):
    return ch == ch[::-1]
ch =input('Enter a word')
ans = isPalindrome(ch)
if ans:
    print("Yes")
else:
    print("No")

Enter a wordaba
Yes


In [23]:
str = "hello, good morning! ;"
print("original string is : " + str)
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for i in str:
    if i in punc:
        str = str.replace(i, "")
print("The string after removing punctuation marks is : " + str)


original string is : hello, good morning! ;
The string after removing punctuation marks is : hello good morning 


In [25]:
str = "Hello I am Pragati"
words = [word.lower() for word in str.split()]
words.sort()
print("The sorted words are:")
for word in words:
   print(word)


The sorted words are:
am
hello
i
pragati


In [26]:
A = {0, 2, 4, 6, 8};
B = {1, 2, 3, 4, 5};
print("Union of E and N is",A | B)
print("Intersection of E and N is",A & B)
print("Difference of E and N is",A- B)
print("Symmetric difference of E and N is",A ^ B)


Union of E and N is {0, 1, 2, 3, 4, 5, 6, 8}
Intersection of E and N is {2, 4}
Difference of E and N is {0, 8, 6}
Symmetric difference of E and N is {0, 1, 3, 5, 6, 8}


In [28]:
vowels = 'aeiou'
str = 'Hello, I am Pragati'
str = str.casefold()
count = {}.fromkeys(vowels,0)
for char in str:
   if char in count:
       count[char] += 1
print(count)


{'a': 3, 'e': 1, 'i': 2, 'o': 1, 'u': 0}


In [31]:
import PIL
from PIL import Image
img = PIL.Image.open("xyz.png")
width, height = img.size
print(str(width) + "x" + str(height))
#you can pass the name of image respectively.

FileNotFoundError: [Errno 2] No such file or directory: 'xyz.png'

In [33]:
str='ABCD'
length=4
for i in range(length):
    for j in range(length-i-1):
        print(" ",end="")
    for j in range(i+1):
        print(str[j],end=" ")
    print()

   A 
  A B 
 A B C 
A B C D 


In [35]:
def mer(dict1,dict2):
    return(dict2.update(dict1))
dict1={'a':1,'b':2}
dict2={'c':3,'d':4}
print(mer(dict1,dict2))
print(dict2)

None
{'c': 3, 'd': 4, 'a': 1, 'b': 2}


In [36]:
l=[10,20,30,40]
for i,val in enumerate(l):
    print(i,val)

0 10
1 20
2 30
3 40


In [37]:
l=[1,2,3,4,5]
print(l[:])
print(l[1:])
print(l[:2])
print(l[::-1])
print(l[1:4])
print(l[::2])
print(l[1:4:2])

[1, 2, 3, 4, 5]
[2, 3, 4, 5]
[1, 2]
[5, 4, 3, 2, 1]
[2, 3, 4]
[1, 3, 5]
[2, 4]


In [38]:
def rem(str):
    return str.replace(" ","")
str='H ell O'
print(rem(str))

HellO


In [39]:
l=['h','e','l','l','o']
print(*l)

h e l l o
